language: node_js
node_js:
  - "6"
stages:
  - name: deploy
    # require the branch name to be master
    if: branch = migrate-es6 # condition
before_script:
  - npm install
script:
    - npm run test
    - npm run build
    - npm run build:prod
cache:
  directories:
    - node_modules
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: migrate-es6 # condition
