# https://docs.travis-ci.com/user/build-stages/
language: node_js
node_js:
  - "6"
stages:
  - name: deploy
    # require the branch name to be master
    if: branch = master # condition
before_script:
  - npm install
script:
    - bash scripts/build.sh
cache:
  directories:
    - node_modules
before_deploy:
    - bash scripts/before_deploy.sh
deploy:
  # deploy from master the current binary and jsdoc
  provider: script
  skip_cleanup: true
  script:
      - bash scripts/deploy.sh
  on:
    branch: master # condition
after_deploy:
    - bash scripts/after_deploy.sh
