name: Build project ...

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - 'release-*'

jobs:

  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run cover

      - name: ESlint
        run: npm run eslint

  publish_samples:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: IGNF/geoportal-access-lib-samples
          ref: develop
          # persist-credentials: false
          # fetch-depth: 0
          token : ${{ secrets.ADMIN_GEOPORTAL_TOKEN }}
    
      - name: Get info
        id: get_info
        run: |
          echo ::set-output name=HASH::$(git rev-parse --short "${GITHUB_SHA}")
          echo ::set-output name=BRANCH::$(echo ${GITHUB_REF#refs/heads/})

      - name: Update build.txt
        run: |
          echo $(date) > build.txt
          echo "repository : geoportal-access-lib" >> build.txt
          echo "branch : ${{ steps.get_info.outputs.BRANCH }}" >> build.txt
          echo "commit : ${{ steps.get_info.outputs.HASH }}" >> build.txt

      - name: Publish
        run: |
          git config user.name IGNF
          git config user.email IGNF@github.com
          git add -A
          git commit -m "update build.txt"
          git push

